permissions:
  contents: write

name: Release APWorld
on:
  push:
    tags:
      - '**'
jobs:
  release:
    uses: Eijebong/ap-actions/.github/workflows/release-apworld.yml@main
    with:
      apworld-path: worlds/melatonin
      ap-version: '0.6.5'
      python-version: '3.12'
